#pragma once

#define SCREEN_WIDTH			800.0f
#define SCREEN_HEIGHT			600.0f
#define SHOOT_RADIUS_Y			0.1f
#define SHOOT_RADIUS_X_PLAYER	0.1f	
#define SHOOT_RADIUS_X_COMP		0.07f
#define CENTER_DISP_PLAYER		0.05f
#define CENTER_DISP_COMP		0.025f
#define OUT_LINE_BOTTOM_LEFT	0.02f
#define OUT_LINE_BOTTOM_RIGHT	0.97f
#define OUT_LINE_TOP_LEFT		0.23f
#define OUT_LINE_TOP_RIGHT		0.75f
#define BALL_SPEED				0.02f
#define COMPUTER_SPEED			0.007f
#define PLAYER_SPEED_X			0.02f
#define PLAYER_SPEED_Y			0.01f
